### ISSUE TITLE
Write (:w) shows error

### ISSUE THREAD

**Issue by arunvelsriram** [aswinkarthik93/neovim-dotfiles#15]
Writing to filesystem shows error after a [recent change](https://github.com/aswinkarthik93/neovim-dotfiles/commit/77479a83ce470baf2f4d187a6d4148aee0db1b78). However content is written to the filesystem successfully.

**Replicating**

1. Open a file
2. Edit it
3. Write `:w`
4. Undo `:u`
5. Write again `:w`

![neovim](https://user-images.githubusercontent.com/6568319/38145633-eaae33da-3467-11e8-9f87-0159901f140a.gif)

**Comment by jskswamy** [comment]
@arunvelsriram are you still seeing this error?

**Comment by arunvelsriram** [comment]
No. It's fixed in [this commit](https://github.com/aswinkarthik93/neovim-dotfiles/commit/5fea09a43c5be4644ac709feaa232acbad4b4e91)
