### ISSUE TITLE
Writing is very slow

### ISSUE THREAD

**Issue by arunvelsriram** [aswinkarthik93/neovim-dotfiles#9]
Writing `ruby`, `javascript` is very slow.

For `ruby` code `rubocop` is making the write slow.
For `javascript` I suspect `prettier`.

**Comment by jskswamy** [comment]
We can disable running rubocop, and neoformat to make it fast but how do we ensure that we run it and ensure the code format is consistent?

**Comment by jskswamy** [comment]
@arunvelsriram @aswinkarthik93 I think this issue is happening since the rubocop is running as part of saving the file, either we can choose to not run it or have or live with it

**Comment by aswinkarthik** [comment]
This is fixed now. Closing it
